from decimal import Decimal

from sqlmodel import Session, select

from app.database import create_db_and_tables, engine
from app.models import Category, Product, ProductVariant, User, UserRole
from app.security import hash_password


def _assert_isolated_db_target() -> None:
    db_url = str(engine.url).lower()
    if "footy.db" in db_url and "footy-smoke.db" not in db_url:
        raise RuntimeError(
            f"Refusing demo seed on shared DB ({engine.url}). "
            "Use isolated FOOTY_DATABASE_URL=sqlite:///./footy-smoke.db."
        )


def main() -> None:
    _assert_isolated_db_target()
    create_db_and_tables()

    with Session(engine) as session:
        category = session.exec(select(Category).where(Category.slug == "demo-footwear")).first()
        if not category:
            category = Category(name="Demo Footwear", slug="demo-footwear", is_active=True)
            session.add(category)
            session.commit()
            session.refresh(category)

        product = session.exec(select(Product).where(Product.slug == "demo-boot")).first()
        if not product:
            product = Product(
                slug="demo-boot",
                name="Demo Boot",
                short_description="Seeded product for local smoke tests",
                description="This product is generated by seed_demo_data.py",
                brand_name="Footy Labs",
                price=Decimal("99.00"),
                currency="KZT",
                category_id=category.id,
                is_active=True,
            )
            session.add(product)
            session.commit()
            session.refresh(product)

        variant = session.exec(select(ProductVariant).where(ProductVariant.sku == "demo-boot-v1")).first()
        if not variant:
            variant = ProductVariant(
                product_id=product.id,
                sku="demo-boot-v1",
                size="M",
                color="Black",
                stock_quantity=1,
                is_active=True,
            )
            session.add(variant)
        else:
            variant.stock_quantity = 1
            variant.is_active = True
            session.add(variant)

        admin = session.exec(select(User).where(User.email == "admin@footy.local")).first()
        if not admin:
            admin = User(
                email="admin@footy.local",
                password_hash=hash_password("adminpass"),
                full_name="Admin",
                role=UserRole.ADMIN,
                is_active=True,
            )
            session.add(admin)

        session.commit()

    print("Seeded demo data: category=demo-footwear, product=demo-boot, admin=admin@footy.local")


if __name__ == "__main__":
    main()
